version: "3.8"

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
  booking:
    depends_on:
      - mysqldb
    build: ./booking-service
    restart: on-failure
    env_file: ./.env
    ports:
      - '8080:8080'
  user:
    depends_on:
      - mysqldb
    build: ./user-service
    restart: on-failure
    env_file: ./.env
    ports:
      - '8081:8080'