# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main", "developer" ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: maven:3.8-eclipse-temurin-17
    
    services:
      mysqldb: 
        image: mysql:8.0.30
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=5
        env:
            MYSQL_DATABASE: sept
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: shrimpfriedrice
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3
        
    - name: Build with Maven
      run: mvn -B package --file booking-service/pom.xml

    - name: Build with Maven
      run: mvn -B package --file user-service/pom.xml
